baseURL = "https://trebaud.github.io/"
languageCode = "en-us"
paginate = 5
tags = ["development", "software", "neovim", "security"]
theme = "hello-friend-trebaud"
title = "trebaud"

googleAnalytics = "G-4BDVPG70H1"

[params]
    description = "My blog"
    keywords = ""
    images = [""]

    showMenuItems = 2
    
    showReadingTime = true
    
    homeSubtitle = "A collection of loosely coupled ramblings about tech, coding and life." 
    
    disableReadOtherPosts = false
    enableThemeToggle = true
    enableSharingButtons = true
    enableComments = true
    missingContentMessage = "??"

[params.utterances]
    owner = "trebaud"
    repo = "trebaud.github.io"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/trebaud"
    logoHomeLink = "/"

[[params.social]]
    name = "github"
    url = "https://github.com/trebaud"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/thomas-rebaud-8017a168/"

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]
    [[menu.main]]
    name = "cd ~/posts"
    url = "/posts"
    weight = 2

    [[menu.main]]
    name = "whoami"
    url = "/whoami"
    weight = 3
    
    [[menu.main]]
    name = "ğŸ” tags"
    url = "/tags"
    weight = 4
    
    [[menu.main]]
    name = "ğŸ¸ guitar"
    url = "/neck-visualizer"
    weight = 5
